# author: "Arham Naqvi"
# date: today
format:
    html:
        toc: true
        standalone: true
        code-fold: true
        code-copy: true
        template: template.html
        js: template.js
        css: template.css
        theme: "null"   # <--- disables Bootstrap theme
    pdf:
        toc: true
        number-sections: true
        documentclass: article
        fontsize: 11pt
        geometry: margin=1in
        citation-style: apa
    gfm:
        toc: true
        code-copy: true