name: Convert Markdown to HTML
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      markdown_url:
        description: 'URL to markdown file'
        required: true
        type: string
      output_path:
        description: 'Output directory and filename (e.g., projects/writeup.html)'
        required: true
        type: string

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Eepository
        uses: actions/checkout@v3
        # with:
        #   token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc
      
      - name: Convert to HTML with TOC
        run: |
          mkdir -p $(dirname "${{ github.event.inputs.output_path }}")
          pandoc -s --toc \
            "${{ github.event.inputs.markdown_url }}" \
            -o "${{ github.event.inputs.output_path }}"
      
      - name: Commit and push
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add "${{ github.event.inputs.output_path }}"
          git commit -m "Add converted markdown: ${{ github.event.inputs.output_path }}"
          git push